services:
  ussp-test-suite:
    container_name: ussp-test-suite
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: ussp-test-suite
    logging:
      driver: fluentd
      options:
        tag: ussp-test-suite
    ports:
      - "8000:8000"
    volumes:
      - "/data"
