from api.constants.auth import (
    CONSTRAINT_MANAGEMENT_SCOPE_VALUE,
    DSS_CLIENT_TYPE,
    INTENDED_AUDIENCE_DSS_VALUE,
    INTENDED_AUDIENCE_USSP_VALUE,
    STRATEGIC_COORDINATION_SCOPE_VALUE,
    USSP_CLIENT_TYPE,
)

scope_switcher = {
    "constraint": CONSTRAINT_MANAGEMENT_SCOPE_VALUE,
    "coordination": STRATEGIC_COORDINATION_SCOPE_VALUE,
}


audience_switcher = {
    USSP_CLIENT_TYPE: INTENDED_AUDIENCE_USSP_VALUE,
    DSS_CLIENT_TYPE: INTENDED_AUDIENCE_DSS_VALUE,
}
