from api.constants.auth import (
    DSS_CLIENT_TYPE,
    INTENDED_AUDIENCE_DSS_VALUE,
    INTENDED_AUDIENCE_USSP_VALUE,
    USSP_CLIENT_TYPE,
)

audience_switcher = {
    USSP_CLIENT_TYPE: INTENDED_AUDIENCE_USSP_VALUE,
    DSS_CLIENT_TYPE: INTENDED_AUDIENCE_DSS_VALUE,
}
